import React, { useState } from 'react';
import Button from '@mui/material/Button';
import IconButton from '@mui/material/IconButton';
import Stack from '@mui/material/Stack';
import Item from '@mui/material/Stack';
import { FormGroup } from '@mui/material';
import { Grid } from '@mui/material';
import { InputAdornment } from '@mui/material';
import TextField from '@mui/material/TextField';
import { AccountCircle } from '@mui/icons-material';
import PasswordIcon from '@mui/icons-material/Password';
import VisibilityIcon from '@mui/icons-material/Visibility';
import { Card } from '@mui/material';
import { Typography } from '@mui/material';
import "./Form.css";

function Form() {

    const [showPassword, setShowPassword] = useState(false);
    const generate = () => {
        //here I will bring the password generated by back-end
    }

    return (
        <FormGroup id="page">
            <Grid id="form">
                <Stack spacing={2}>
                    <Item><h>My password generator</h></Item>
                    <Item>
                        <div>
                            <AccountCircle className='form-icon' fontSize='large' />
                            <TextField id="user-id"
                                label="User id" variant="outlined"
                                helperText="Enter your id to generate a one time password">
                            </TextField>
                        </div>
                        <div>
                            <Button onClick={generate}>Generate password</Button>
                        </div>
                        <Item>
                            <div>
                                <PasswordIcon className='form-icon' fontSize='large' />
                                <TextField id="password" type={showPassword ? "text" : "password"}
                                    label="Password" variant="outlined"
                                    helperText="Notice that: Password expiers in 30 sec."
                                    InputProps={{
                                        endAdornment: <InputAdornment position="end">
                                            <IconButton ton style={{ color: "#a742f5" }} >
                                                <VisibilityIcon onClick={() => setShowPassword(s => !s)} />
                                            </IconButton >
                                        </InputAdornment>,
                                    }}>
                                </TextField>
                            </div>
                            <div>
                                <Button>Login</Button>
                                <Button>Reset</Button>
                            </div>
                            <Card>
                                <Typography sx={{ fontSize: 14 }} color="text.secondary" gutterBottom> Your one time password is:
                                </Typography>
                                <Typography variant="h5" component="div">   AFv5%h8*
                                </Typography>
                                <Typography sx={{ mb: 1.5 }} color="text.secondary">Hurry! It expiers in 30 seconds!
                                </Typography>
                            </Card>
                        </Item>
                    </Item>
                </Stack>
            </Grid>
        </FormGroup>
    );
}

export default Form;